.class public Lcom/android/settings/Settings;
.super Lcom/android/settings/SettingsActivity;
.source "Settings.java"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/android/settings/Settings$OPCustomFingerprintAnimSettingsActivity;,
        Lcom/android/settings/Settings$SMQQtiFeedbackActivity;,
        Lcom/android/settings/Settings$SupportDashboardActivity;,
        Lcom/android/settings/Settings$MyDeviceInfoFragmentActivity;,
        Lcom/android/settings/Settings$LegalSettingsActivity;,
        Lcom/android/settings/Settings$PowerUsageAdvancedActivity;,
        Lcom/android/settings/Settings$OPCloudServiceSettings;,
        Lcom/android/settings/Settings$BgOptimizeSwitchActivity;,
        Lcom/android/settings/Settings$BgOptimizeAppListActivity;,
        Lcom/android/settings/Settings$OPDataUsageSummaryActivity;,
        Lcom/android/settings/Settings$OPDeviceNameActivity;,
        Lcom/android/settings/Settings$OPVibrationModeActivity;,
        Lcom/android/settings/Settings$OPSilentModeActivity;,
        Lcom/android/settings/Settings$OPRingModeActivity;,
        Lcom/android/settings/Settings$OPButtonsAndGesturesSettingsActivity;,
        Lcom/android/settings/Settings$OPNotificationAndNotdisturbSettingsActivity;,
        Lcom/android/settings/Settings$OPEarphoneModeActivity;,
        Lcom/android/settings/Settings$DisplaySizeAdaptionAppListActivity;,
        Lcom/android/settings/Settings$DomainsURLsAppListActivity;,
        Lcom/android/settings/Settings$AllApplicationsActivity;,
        Lcom/android/settings/Settings$DefaultAssistPickerActivity;,
        Lcom/android/settings/Settings$OPDataSaverActivity;,
        Lcom/android/settings/Settings$OPProductInfoActivity;,
        Lcom/android/settings/Settings$OPPreInstalledAppListActivity;,
        Lcom/android/settings/Settings$OPReadingModeActivity;,
        Lcom/android/settings/Settings$OPNightModeActivity;,
        Lcom/android/settings/Settings$OPAppLockerActivity;,
        Lcom/android/settings/Settings$OPGamingModeActivity;,
        Lcom/android/settings/Settings$OPQuickLaunchListSettings;,
        Lcom/android/settings/Settings$OPQuickLaunchSettings;,
        Lcom/android/settings/Settings$OPQuickPaySettingsActivity;,
        Lcom/android/settings/Settings$OPToolsSettingsActivity;,
        Lcom/android/settings/Settings$OPGestureAnswerSettings;,
        Lcom/android/settings/Settings$OPFaceUnlockSettings;,
        Lcom/android/settings/Settings$SystemDashboardActivity;,
        Lcom/android/settings/Settings$AccountDashboardActivity;,
        Lcom/android/settings/Settings$StorageDashboardActivity;,
        Lcom/android/settings/Settings$AppAndNotificationDashboardActivity;,
        Lcom/android/settings/Settings$PowerUsageSummaryActivity;,
        Lcom/android/settings/Settings$ConnectedDeviceDashboardActivity;,
        Lcom/android/settings/Settings$NetworkDashboardActivity;,
        Lcom/android/settings/Settings$AdvancedConnectedDeviceActivity;,
        Lcom/android/settings/Settings$WebViewAppPickerActivity;,
        Lcom/android/settings/Settings$EnterprisePrivacySettingsActivity;,
        Lcom/android/settings/Settings$WifiInfoActivity;,
        Lcom/android/settings/Settings$WifiAPITestActivity;,
        Lcom/android/settings/Settings$TestingSettingsActivity;,
        Lcom/android/settings/Settings$IccLockSettingsActivity;,
        Lcom/android/settings/Settings$ChooseAccountActivity;,
        Lcom/android/settings/Settings$ApnEditorActivity;,
        Lcom/android/settings/Settings$DeletionHelperActivity;,
        Lcom/android/settings/Settings$ManagedProfileSettingsActivity;,
        Lcom/android/settings/Settings$WallpaperSettingsActivity;,
        Lcom/android/settings/Settings$ManageAppExternalSourcesActivity;,
        Lcom/android/settings/Settings$ManageExternalSourcesActivity;,
        Lcom/android/settings/Settings$AdvancedAppsActivity;,
        Lcom/android/settings/Settings$AppWriteSettingsActivity;,
        Lcom/android/settings/Settings$AppDrawOverlaySettingsActivity;,
        Lcom/android/settings/Settings$ChangeWifiStateActivity;,
        Lcom/android/settings/Settings$WriteSettingsActivity;,
        Lcom/android/settings/Settings$OverlaySettingsActivity;,
        Lcom/android/settings/Settings$AppMemoryUsageActivity;,
        Lcom/android/settings/Settings$MemorySettingsActivity;,
        Lcom/android/settings/Settings$WifiCallingSettingsActivity;,
        Lcom/android/settings/Settings$ApnSettingsActivity;,
        Lcom/android/settings/Settings$TopLevelSettings;,
        Lcom/android/settings/Settings$DirectoryAccessSettingsActivity;,
        Lcom/android/settings/Settings$PhotosStorageActivity;,
        Lcom/android/settings/Settings$MoviesStorageActivity;,
        Lcom/android/settings/Settings$GamesStorageActivity;,
        Lcom/android/settings/Settings$AutomaticStorageManagerSettingsActivity;,
        Lcom/android/settings/Settings$ManageDomainUrlsActivity;,
        Lcom/android/settings/Settings$ChannelGroupNotificationSettingsActivity;,
        Lcom/android/settings/Settings$ChannelNotificationSettingsActivity;,
        Lcom/android/settings/Settings$AppNotificationSettingsActivity;,
        Lcom/android/settings/Settings$NotificationAppListActivity;,
        Lcom/android/settings/Settings$ConfigureNotificationSettingsActivity;,
        Lcom/android/settings/Settings$SoundSettingsActivity;,
        Lcom/android/settings/Settings$ZenModeEventRuleSettingsActivity;,
        Lcom/android/settings/Settings$ZenModeScheduleRuleSettingsActivity;,
        Lcom/android/settings/Settings$ZenModeAutomationSettingsActivity;,
        Lcom/android/settings/Settings$ZenModeBlockedEffectsSettingsActivity;,
        Lcom/android/settings/Settings$ZenModeBehaviorSettingsActivity;,
        Lcom/android/settings/Settings$ZenModeSettingsActivity;,
        Lcom/android/settings/Settings$PrintJobSettingsActivity;,
        Lcom/android/settings/Settings$PrintSettingsActivity;,
        Lcom/android/settings/Settings$PaymentSettingsActivity;,
        Lcom/android/settings/Settings$TrustedCredentialsSettingsActivity;,
        Lcom/android/settings/Settings$UsbDetailsActivity;,
        Lcom/android/settings/Settings$UsbSettingsActivity;,
        Lcom/android/settings/Settings$ConditionProviderSettingsActivity;,
        Lcom/android/settings/Settings$ZenAccessSettingsActivity;,
        Lcom/android/settings/Settings$AppPictureInPictureSettingsActivity;,
        Lcom/android/settings/Settings$PictureInPictureSettingsActivity;,
        Lcom/android/settings/Settings$VrListenersSettingsActivity;,
        Lcom/android/settings/Settings$NotificationAccessSettingsActivity;,
        Lcom/android/settings/Settings$UserSettingsActivity;,
        Lcom/android/settings/Settings$NotificationStationActivity;,
        Lcom/android/settings/Settings$DreamSettingsActivity;,
        Lcom/android/settings/Settings$WifiDisplaySettingsActivity;,
        Lcom/android/settings/Settings$AndroidBeamSettingsActivity;,
        Lcom/android/settings/Settings$TextToSpeechSettingsActivity;,
        Lcom/android/settings/Settings$SavedAccessPointsSettingsActivity;,
        Lcom/android/settings/Settings$ConfigureWifiSettingsActivity;,
        Lcom/android/settings/Settings$MobileDataUsageListActivity;,
        Lcom/android/settings/Settings$DataUsageSummaryLegacyActivity;,
        Lcom/android/settings/Settings$DataUsageSummaryActivity;,
        Lcom/android/settings/Settings$DeviceAdminSettingsActivity;,
        Lcom/android/settings/Settings$CryptKeeperSettingsActivity;,
        Lcom/android/settings/Settings$AccountSyncSettingsInAddAccountActivity;,
        Lcom/android/settings/Settings$AccountSyncSettingsActivity;,
        Lcom/android/settings/Settings$BatterySaverSettingsActivity;,
        Lcom/android/settings/Settings$RunningServicesActivity;,
        Lcom/android/settings/Settings$FactoryResetActivity;,
        Lcom/android/settings/Settings$PrivacySettingsActivity;,
        Lcom/android/settings/Settings$ScanningSettingsActivity;,
        Lcom/android/settings/Settings$LocationSettingsActivity;,
        Lcom/android/settings/Settings$UsageAccessSettingsActivity;,
        Lcom/android/settings/Settings$SecurityDashboardActivity;,
        Lcom/android/settings/Settings$AccessibilityDaltonizerSettingsActivity;,
        Lcom/android/settings/Settings$AccessibilityContrastSettingsActivity;,
        Lcom/android/settings/Settings$AccessibilityInversionSettingsActivity;,
        Lcom/android/settings/Settings$CaptioningSettingsActivity;,
        Lcom/android/settings/Settings$AccessibilitySettingsActivity;,
        Lcom/android/settings/Settings$DevelopmentSettingsDashboardActivity;,
        Lcom/android/settings/Settings$StorageUseActivity;,
        Lcom/android/settings/Settings$BackgroundCheckSummaryActivity;,
        Lcom/android/settings/Settings$HighPowerApplicationsActivity;,
        Lcom/android/settings/Settings$ManageAssistActivity;,
        Lcom/android/settings/Settings$ManageApplicationsActivity;,
        Lcom/android/settings/Settings$ApplicationSettingsActivity;,
        Lcom/android/settings/Settings$MyDeviceInfoActivity;,
        Lcom/android/settings/Settings$OPAboutPhoneActivity;,
        Lcom/android/settings/Settings$DeviceInfoSettingsActivity;,
        Lcom/android/settings/Settings$NightDisplaySuggestionActivity;,
        Lcom/android/settings/Settings$NightDisplaySettingsActivity;,
        Lcom/android/settings/Settings$DisplaySettingsActivity;,
        Lcom/android/settings/Settings$UserDictionarySettingsActivity;,
        Lcom/android/settings/Settings$LanguageAndInputSettingsActivity;,
        Lcom/android/settings/Settings$LocalePickerActivity;,
        Lcom/android/settings/Settings$SpellCheckersSettingsActivity;,
        Lcom/android/settings/Settings$InputMethodAndSubtypeEnablerActivity;,
        Lcom/android/settings/Settings$PhysicalKeyboardActivity;,
        Lcom/android/settings/Settings$KeyboardLayoutPickerActivity;,
        Lcom/android/settings/Settings$AvailableVirtualKeyboardActivity;,
        Lcom/android/settings/Settings$WifiP2pSettingsActivity;,
        Lcom/android/settings/Settings$WifiSettingsActivity;,
        Lcom/android/settings/Settings$PublicVolumeSettingsActivity;,
        Lcom/android/settings/Settings$PrivateVolumeSettingsActivity;,
        Lcom/android/settings/Settings$PrivateVolumeForgetActivity;,
        Lcom/android/settings/Settings$DateTimeSettingsActivity;,
        Lcom/android/settings/Settings$VpnSettingsActivity;,
        Lcom/android/settings/Settings$TetherSettingsActivity;,
        Lcom/android/settings/Settings$SimSettingsActivity;,
        Lcom/android/settings/Settings$BluetoothSettingsActivity;,
        Lcom/android/settings/Settings$AssistGestureSettingsActivity;
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    .line 26
    invoke-direct {p0}, Lcom/android/settings/SettingsActivity;-><init>()V

    return-void
.end method
